//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMSFMFireGrantWF.Admin
{
  public partial class EmailSendLog
  {
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvError;

    protected global::System.Web.UI.WebControls.CheckBox chkFailedEmailLogsOnly;

    protected global::System.Web.UI.WebControls.GridView gvEmailSendLog;

    protected global::System.Web.UI.WebControls.Button btnRefreshEmailLog;

    protected global::System.Web.UI.WebControls.Label lblPurgeRetention;

    protected global::System.Web.UI.WebControls.DropDownList ddlPurgeRetention;

    protected global::System.Web.UI.WebControls.Button btnPurgeConfirm;

    protected global::System.Web.UI.WebControls.Label lblEmailTestTo;

    protected global::System.Web.UI.WebControls.TextBox txtEmailTestTo;

    protected global::System.Web.UI.WebControls.Button btnEmailTest;
  }
}
