//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMSFMFireGrantWF.Admin
{
  public partial class ManageAgencyInformation
  {
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvError;
    protected global::System.Web.UI.WebControls.HiddenField hfAgencyId;
    protected global::System.Web.UI.WebControls.HiddenField hfClearReportImage;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvAgencyModalError;
    protected global::System.Web.UI.WebControls.CheckBox chkInactive;
    protected global::System.Web.UI.WebControls.Label lblAgencyName;
    protected global::System.Web.UI.WebControls.TextBox txtAgencyName;
    protected global::System.Web.UI.WebControls.Label lblAgencySubName;
    protected global::System.Web.UI.WebControls.TextBox txtAgencySubName;
    protected global::System.Web.UI.WebControls.Label lblAddress;
    protected global::System.Web.UI.WebControls.TextBox txtAddress;
    protected global::System.Web.UI.WebControls.Label lblCity;
    protected global::System.Web.UI.WebControls.TextBox txtCity;
    protected global::System.Web.UI.WebControls.Label lblStateZip;
    protected global::System.Web.UI.WebControls.DropDownList ddlState;
    protected global::System.Web.UI.WebControls.TextBox txtZip;
    protected global::System.Web.UI.WebControls.Label lblCountry;
    protected global::System.Web.UI.WebControls.DropDownList ddlCountry;
    protected global::System.Web.UI.WebControls.Label lblPhone;
    protected global::System.Web.UI.WebControls.TextBox txtPhone;
    protected global::System.Web.UI.WebControls.Label lblFax;
    protected global::System.Web.UI.WebControls.TextBox txtFax;
    protected global::System.Web.UI.WebControls.Label lblEmail;
    protected global::System.Web.UI.WebControls.TextBox txtEmail;
    protected global::System.Web.UI.WebControls.Label lblReportImage;
    protected global::System.Web.UI.WebControls.Image imgReportPreview;
    protected global::System.Web.UI.WebControls.FileUpload fuReportImage;
    protected global::System.Web.UI.WebControls.Button btnClearReportImage;
    protected global::System.Web.UI.WebControls.PlaceHolder phAdvancedUdf;
    protected global::System.Web.UI.WebControls.Label lblNoUdfFields;
    protected global::System.Web.UI.WebControls.Label lblTechnicalSupportEmail;
    protected global::System.Web.UI.WebControls.TextBox txtTechnicalSupportEmail;
    protected global::System.Web.UI.WebControls.Label lblFireServicesSupportEmail;
    protected global::System.Web.UI.WebControls.TextBox txtFireServicesSupportEmail;
    protected global::System.Web.UI.WebControls.Label lblDateInserted;
    protected global::System.Web.UI.WebControls.Label lblDateUpdated;
    protected global::System.Web.UI.HtmlControls.HtmlButton btnSaveAgency;
  }
}
