using System.Data.Entity;

namespace NMSFM.Data
{
	public interface ICodepalWebModel
	{
		DbSet<ActivityCheckList> ActivityCheckLists { get; set; }
		DbSet<ActivityInventoryItem> ActivityInventoryItems { get; set; }
		DbSet<ActivityPermit> ActivityPermits { get; set; }
		DbSet<ActivitySetting> ActivitySettings { get; set; }
		DbSet<ActivityTypeCaus> ActivityTypeCauses { get; set; }
		DbSet<ActivityTypeGrid> ActivityTypeGrids { get; set; }
		DbSet<ActivityTypeItemType> ActivityTypeItemTypes { get; set; }
		DbSet<ActivityType> ActivityTypes { get; set; }
		DbSet<Address> Addresses { get; set; }
		DbSet<AddressMap> AddressMaps { get; set; }
		DbSet<AddressParty> AddressParties { get; set; }
		DbSet<AddressSetting> AddressSettings { get; set; }
		DbSet<AddressType> AddressTypes { get; set; }
		DbSet<Agency> Agencies { get; set; }
		DbSet<AgencyActivityType> AgencyActivityTypes { get; set; }
		DbSet<Agreement> Agreements { get; set; }
		DbSet<AgreementType> AgreementTypes { get; set; }
		DbSet<ApprovalStep> ApprovalSteps { get; set; }
		DbSet<ArchiveDB> ArchiveDBs { get; set; }
		DbSet<Assignment> Assignments { get; set; }
		DbSet<AssociatedActivity> AssociatedActivities { get; set; }
		DbSet<CalcType> CalcTypes { get; set; }
		DbSet<CategoryType> CategoryTypes { get; set; }
		DbSet<Certification> Certifications { get; set; }
		DbSet<CertificationType> CertificationTypes { get; set; }
		DbSet<CheckItemCalc> CheckItemCalcs { get; set; }
		DbSet<CheckItemCalcVal> CheckItemCalcVals { get; set; }
		DbSet<CheckItem> CheckItems { get; set; }
		DbSet<CheckItemType> CheckItemTypes { get; set; }
		DbSet<CheckItemValueInspectionDetail> CheckItemValueInspectionDetails { get; set; }
		DbSet<CheckItemValue> CheckItemValues { get; set; }
		DbSet<CheckItemViolationType> CheckItemViolationTypes { get; set; }
		DbSet<CheckListActivityType> CheckListActivityTypes { get; set; }
		DbSet<ChecklistIcon> ChecklistIcons { get; set; }
		DbSet<CheckList> CheckLists { get; set; }
		DbSet<CheckListType> CheckListTypes { get; set; }
		DbSet<CheckListValue> CheckListValues { get; set; }
		DbSet<CodeVersionAgency> CodeVersionAgencies { get; set; }
		DbSet<CodeVersion> CodeVersions { get; set; }
		DbSet<Comment> Comments { get; set; }
		DbSet<ComplaintActivity> ComplaintActivities { get; set; }
		DbSet<ComplaintParty> ComplaintParties { get; set; }
		DbSet<ComplaintPermit> ComplaintPermits { get; set; }
		DbSet<Complaint> Complaints { get; set; }
		DbSet<ComplaintStatu> ComplaintStatus { get; set; }
		DbSet<ComplaintType> ComplaintTypes { get; set; }
		DbSet<County> Counties { get; set; }
		DbSet<Country> Countries { get; set; }
		DbSet<DefaultFee> DefaultFees { get; set; }
		DbSet<FeePayment> FeePayments { get; set; }
		DbSet<Fee> Fees { get; set; }
		DbSet<FeeSchedule> FeeSchedules { get; set; }
		DbSet<FeeSetting> FeeSettings { get; set; }
		DbSet<FeesPT> FeesPTs { get; set; }
		DbSet<FeeTypeCon> FeeTypeCons { get; set; }
		DbSet<FeeTypePen> FeeTypePens { get; set; }
		DbSet<FeeTypePT> FeeTypePTs { get; set; }
		DbSet<FeeTypeRR> FeeTypeRRs { get; set; }
		DbSet<FeeType> FeeTypes { get; set; }
		DbSet<File> Files { get; set; }
		DbSet<Group> Groups { get; set; }
		DbSet<InspectionCaus> InspectionCauses { get; set; }
		DbSet<InspectionDetail> InspectionDetails { get; set; }
		DbSet<Inspection> Inspections { get; set; }
		DbSet<InspectionType> InspectionTypes { get; set; }
		DbSet<InspectorGroup> InspectorGroups { get; set; }
		DbSet<Inspector> Inspectors { get; set; }
		DbSet<InventoryItem> InventoryItems { get; set; }
		DbSet<InventoryItemType> InventoryItemTypes { get; set; }
		DbSet<InvNarrative> InvNarratives { get; set; }
		DbSet<InvNarrativeText> InvNarrativeTexts { get; set; }
		DbSet<InvoicePayment> InvoicePayments { get; set; }
		DbSet<Invoice> Invoices { get; set; }
		DbSet<InvoiceSetting> InvoiceSettings { get; set; }
		DbSet<InvoiceType> InvoiceTypes { get; set; }
		DbSet<ItemInspectionStatu> ItemInspectionStatus { get; set; }
		DbSet<ItemLocDesc> ItemLocDescs { get; set; }
		DbSet<Item> Items { get; set; }
		DbSet<ItemSetting> ItemSettings { get; set; }
		DbSet<ItemsStatu> ItemsStatus { get; set; }
		DbSet<ItemType> ItemTypes { get; set; }
		DbSet<License> Licenses { get; set; }
		DbSet<LicenseDevice> LicenseDevices { get; set; }
		DbSet<ListViewSave> ListViewSaves { get; set; }
		DbSet<LocationBas> LocationBases { get; set; }
		DbSet<Location> Locations { get; set; }
		DbSet<LocationSetting> LocationSettings { get; set; }
		DbSet<LocationType> LocationTypes { get; set; }
		DbSet<Memorandum> Memorandums { get; set; }
		DbSet<Mileage> Mileages { get; set; }
		DbSet<Module> Modules { get; set; }
		DbSet<ModuleTypeReport> ModuleTypeReports { get; set; }
		DbSet<Note> Notes { get; set; }
		DbSet<NumberSchema> NumberSchemas { get; set; }
		DbSet<OccupancyType> OccupancyTypes { get; set; }
		DbSet<Party> Parties { get; set; }
		DbSet<PartyPriceLevel> PartyPriceLevels { get; set; }
		DbSet<PartyRole> PartyRoles { get; set; }
		DbSet<PermitCertificateType> PermitCertificateTypes { get; set; }
		DbSet<Permit> Permits { get; set; }
		DbSet<PermitSetting> PermitSettings { get; set; }
		DbSet<PermitStatu> PermitStatus { get; set; }
		DbSet<PermitSub> PermitSubs { get; set; }
		DbSet<PermitTypeActList> PermitTypeActLists { get; set; }
		DbSet<PermitType> PermitTypes { get; set; }
		DbSet<Phone> Phones { get; set; }
		DbSet<PhoneType> PhoneTypes { get; set; }
		DbSet<ProjectActivity> ProjectActivities { get; set; }
		DbSet<ProjectAddress> ProjectAddresses { get; set; }
		DbSet<ProjectInspector> ProjectInspectors { get; set; }
		DbSet<ProjectPermit> ProjectPermits { get; set; }
		DbSet<ProjectRequest> ProjectRequests { get; set; }
		DbSet<Project> Projects { get; set; }
		DbSet<ProjectSetting> ProjectSettings { get; set; }
		DbSet<ProjectStatu> ProjectStatus { get; set; }
		DbSet<ProjectType> ProjectTypes { get; set; }
		DbSet<ProjectTypesDefault> ProjectTypesDefaults { get; set; }
		DbSet<PropertyUseType> PropertyUseTypes { get; set; }
		DbSet<Region> Regions { get; set; }
		DbSet<ReportDataDefinition> ReportDataDefinitions { get; set; }
		DbSet<ReportDefinition> ReportDefinitions { get; set; }
		DbSet<ReportGroup> ReportGroups { get; set; }
		DbSet<Report> Reports { get; set; }
		DbSet<ReportSQL> ReportSQLs { get; set; }
		DbSet<ReportUserGroup> ReportUserGroups { get; set; }
		DbSet<ReportWizardDefinition> ReportWizardDefinitions { get; set; }
		DbSet<RequestSetting> RequestSettings { get; set; }
		DbSet<Resolution> Resolutions { get; set; }
		DbSet<RoleType> RoleTypes { get; set; }
		DbSet<Route> Routes { get; set; }
		DbSet<RoutingSlip> RoutingSlips { get; set; }
		DbSet<SearchDisplay> SearchDisplays { get; set; }
		DbSet<ServiceHistory> ServiceHistories { get; set; }
		DbSet<ServiceTypeActivityType> ServiceTypeActivityTypes { get; set; }
		DbSet<ServiceTypeItemType> ServiceTypeItemTypes { get; set; }
		DbSet<ServiceType> ServiceTypes { get; set; }
		DbSet<Setting> Settings { get; set; }
		DbSet<Severity> Severities { get; set; }
		DbSet<SeverityActivityType> SeverityActivityTypes { get; set; }
		DbSet<Signature> Signatures { get; set; }
		DbSet<SignatureType> SignatureTypes { get; set; }
		DbSet<SignOffItem> SignOffItems { get; set; }
		DbSet<SignOffObjectUser> SignOffObjectUsers { get; set; }
		DbSet<SignOffType> SignOffTypes { get; set; }
		DbSet<SignOffUser> SignOffUsers { get; set; }
		DbSet<SignOffUserPosting> SignOffUserPostings { get; set; }
		DbSet<SignOffValue> SignOffValues { get; set; }
		DbSet<State> States { get; set; }
		DbSet<SyncSetting> SyncSettings { get; set; }
		DbSet<SystemItem> SystemItems { get; set; }
		DbSet<SystemTemplate> SystemTemplates { get; set; }
		DbSet<Term> Terms { get; set; }
		DbSet<UDFCategoriesIcon> UDFCategoriesIcons { get; set; }
		DbSet<UserDefCategory> UserDefCategories { get; set; }
		DbSet<UserDefCategoryType> UserDefCategoryTypes { get; set; }
		DbSet<UserDefField> UserDefFields { get; set; }
		DbSet<UserDefGlobalField> UserDefGlobalFields { get; set; }
		DbSet<UserDefType> UserDefTypes { get; set; }
		DbSet<UserDefValue> UserDefValues { get; set; }
		DbSet<Version> Versions { get; set; }
		DbSet<ViolationSearchCriteriaType> ViolationSearchCriteriaTypes { get; set; }
		DbSet<ViolationType> ViolationTypes { get; set; }

		//Added for NMSFM Fire Protection Fund Distribution
		DbSet<FYStatuteDist> FYStatuteDists { get; set; }
		DbSet<FYAllowableDist> FYAllowableDists { get; set; }
		DbSet<FYTotalDist> FYTotalDists { get; set; }
		DbSet<FYTotalDistCalc> FYTotalDistCalcs { get; set; }		
		DbSet<FYApplication> FYApplications { get; set; }
		DbSet<FYAppData> FYAppDatas { get; set; }
		DbSet<FYAppStation> FYAppStations { get; set; }
		DbSet<nm_FYTotalDistribution> nm_FYTotalDistributions { get; set; }
		DbSet<nm_FYTotalDistributionCalc> nm_FYTotalDistributionCalcs { get; set; }
		DbSet<nm_FYDetailedApplication> nm_FYDetailedApplications { get; set; }
		DbSet<FYInvoices> FYInvoices { get; set; }
		DbSet<nm_FYDistributionInvoice>  nm_FYDistributionInvoice { get; set; }
		//END Additions for NMSFM Fire Protection Fund Distribution

		//Added for NMSFM Fire Grant Funds
		DbSet<FGApplicationSettings> FGApplicationSettings { get; set; }
		DbSet<FGApplications> FGApplications { get; set; }
		DbSet<FG_App_GeneralInfo> FG_App_GeneralInfos { get; set; }
		DbSet<FG_App_BudgetInfo> FG_App_BudgetInfos { get; set; }
		DbSet<FG_App_CommunityInfo> FG_App_CommunityInfos { get; set; }
		DbSet<FG_App_AidDistricts> FG_App_AidDistricts { get; set; }
		DbSet<FG_App_ResponseHistory> FG_App_ResponseHistories { get; set; }
		DbSet<FG_App_WaterAvailability> FG_App_WaterAvailabilities { get; set; }
		DbSet<FG_App_WaterSources> FG_App_WaterSources { get; set; }
		DbSet<FG_App_Training> FG_App_Trainings { get; set; }
		DbSet<FG_App_TrainingOpportunities> FG_App_TrainingOpportunities { get; set; }
		DbSet<FG_App_Apparatus> FG_App_Apparatuses { get; set; }
		DbSet<FG_App_ApparatusEquipment> FG_App_ApparatusEquipment { get; set; }
		DbSet<FG_App_Communication> FG_App_Communications { get; set; }
		DbSet<FG_App_CommunicationEquipment> FG_App_CommunicationEquipment { get; set; }
		DbSet<FG_App_HazardsThreats> FG_App_HazardsThreats { get; set; }
		DbSet<FG_App_HazardThreatEvents> FG_App_HazardThreatEvents { get; set; }
		DbSet<FG_App_PPE> FG_App_PPEs { get; set; }
		DbSet<FG_App_StandardPPE> FG_App_StandardPPEs { get; set; }
		DbSet<FG_App_StandardSCBA> FG_App_StandardSCBAs { get; set; }
		DbSet<FG_App_EquipmentNeeds> FG_App_EquipmentNeeds { get; set; }
		DbSet<FG_App_ApplicationEquipment> FG_App_ApplicationEquipments { get; set; }
		DbSet<FG_App_FundingJustification> FG_App_FundingJustifications { get; set; }
		DbSet<nm_FGApplication> nm_FGApplications { get; set; }
		DbSet<nm_FGApplicationReport> nm_FGApplicationReport { get; set; }
		DbSet<FG_App_ProjectBudget> FG_App_ProjectBudgets { get; set; }
		DbSet<FG_App_DocsSigs> FG_App_DocsSigs { get; set; }
		DbSet<FG_App_Signatures> FG_App_Signatures { get; set; }
		DbSet<FG_App_Documents> FG_App_Documents { get; set; }
		DbSet<FG_Priorities> FG_Priorities { get; set; }
		DbSet<FG_Categories> FG_Categories { get; set; }
		DbSet<FG_FDIDs> FG_FDIDs { get; set; }
		DbSet<FG_App_Review> FG_App_Reviews { get; set; }
		DbSet<FG_App_Help> FG_App_Helps { get; set; }
		DbSet<FG_App_Scores> FG_App_Scores { get; set; }

		//END Additions for NMSFM Fire Grant Funds

		DbSet<Zip> Zips { get; set; }
		DbSet<zzPartyWebAccess> zzPartyWebAccess { get; set; }
		DbSet<zzHelp> zzHelp { get; set; }
		DbSet<v_Activities> v_Activities { get; set; }
		DbSet<v_Activities2> v_Activities2 { get; set; }
		DbSet<v_Activities3> v_Activities3 { get; set; }
		DbSet<v_ActivitiesRW> v_ActivitiesRW { get; set; }
		DbSet<v_ActivitiesTwo> v_ActivitiesTwo { get; set; }
		DbSet<v_ActivitiesUDF> v_ActivitiesUDF { get; set; }
		DbSet<v_Activity> v_Activity { get; set; }
		DbSet<v_ActivityChecklists> v_ActivityChecklists { get; set; }
		DbSet<v_ActivityComplaints> v_ActivityComplaints { get; set; }
		DbSet<v_ActivityPermits> v_ActivityPermits { get; set; }
		DbSet<v_AddLatLon> v_AddLatLon { get; set; }
		DbSet<v_Addresses> v_Addresses { get; set; }
		DbSet<v_Addresses2> v_Addresses2 { get; set; }
		DbSet<v_AddressesReport> v_AddressesReport { get; set; }
		DbSet<v_AddressesReportNA> v_AddressesReportNA { get; set; }
		DbSet<v_AddressParties> v_AddressParties { get; set; }
		DbSet<v_AddressPartyandRole> v_AddressPartyandRole { get; set; }
		DbSet<v_Agency> v_Agency { get; set; }
		DbSet<v_Agreements> v_Agreements { get; set; }
		DbSet<v_Alerts> v_Alerts { get; set; }
		DbSet<v_AlertsNR> v_AlertsNR { get; set; }
		DbSet<v_Assignments> v_Assignments { get; set; }
		DbSet<v_AssocActivities> v_AssocActivities { get; set; }
		DbSet<v_AssocActivities2> v_AssocActivities2 { get; set; }
		DbSet<v_Certifications> v_Certifications { get; set; }
		DbSet<v_CheckItemCalcValues> v_CheckItemCalcValues { get; set; }
		DbSet<v_CheckItemCalcValuesFirePump> v_CheckItemCalcValuesFirePump { get; set; }
		DbSet<v_CheckItemCalcValuesFirePumpDiesel> v_CheckItemCalcValuesFirePumpDiesel { get; set; }
		DbSet<v_CheckItemValues> v_CheckItemValues { get; set; }
		DbSet<v_CheckItemViolationTypes> v_CheckItemViolationTypes { get; set; }
		DbSet<v_CLInspDet> v_CLInspDet { get; set; }
		DbSet<v_ComplaintActivities> v_ComplaintActivities { get; set; }
		DbSet<v_ComplaintParties> v_ComplaintParties { get; set; }
		DbSet<v_ComplaintPermits> v_ComplaintPermits { get; set; }
		DbSet<v_Complaints> v_Complaints { get; set; }
		DbSet<v_Complaints_old> v_Complaints_old { get; set; }
		DbSet<v_Complaints1> v_Complaints1 { get; set; }
		DbSet<v_FailedSubCheckItems> v_FailedSubCheckItems { get; set; }
		DbSet<v_FeeBalanceSummary> v_FeeBalanceSummary { get; set; }
		DbSet<v_FeePayments> v_FeePayments { get; set; }
		DbSet<v_Fees> v_Fees { get; set; }
		DbSet<v_FeesPermits> v_FeesPermits { get; set; }
		DbSet<v_FeesRecalc> v_FeesRecalc { get; set; }
		DbSet<v_FeesReport> v_FeesReport { get; set; }
		DbSet<v_Files> v_Files { get; set; }
		DbSet<v_InspectionDetails> v_InspectionDetails { get; set; }
		DbSet<v_InspectionDetailsReports> v_InspectionDetailsReports { get; set; }
		DbSet<v_InspectionDetailsUDF> v_InspectionDetailsUDF { get; set; }
		DbSet<v_InventoryItems> v_InventoryItems { get; set; }
		DbSet<v_InvNarratives> v_InvNarratives { get; set; }
		DbSet<v_InvoicePayments> v_InvoicePayments { get; set; }
		DbSet<v_Invoices> v_Invoices { get; set; }
		DbSet<v_InvoiceSummary> v_InvoiceSummary { get; set; }
		DbSet<v_ItemGrid> v_ItemGrid { get; set; }
		DbSet<v_ItemGridAct> v_ItemGridAct { get; set; }
		DbSet<v_ItemInspectionStatus> v_ItemInspectionStatus { get; set; }
		DbSet<v_ItemList> v_ItemList { get; set; }
		DbSet<v_ItemList2> v_ItemList2 { get; set; }
		DbSet<v_Items> v_Items { get; set; }
		DbSet<v_LastActivityAtAddress> v_LastActivityAtAddress { get; set; }
		DbSet<v_LocationItemCount> v_LocationItemCount { get; set; }
		DbSet<v_Locations> v_Locations { get; set; }
		DbSet<v_LocationsCount> v_LocationsCount { get; set; }
		DbSet<v_Mileage> v_Mileage { get; set; }
		DbSet<v_ModuleAliases> v_ModuleAliases { get; set; }
		DbSet<v_OSInspectionDetailsReports> v_OSInspectionDetailsReports { get; set; }
		DbSet<v_OutstandingChecklists> v_OutstandingChecklists { get; set; }
		DbSet<v_Parties> v_Parties { get; set; }
		DbSet<v_PartyAddresses> v_PartyAddresses { get; set; }
		DbSet<v_PaymentSum> v_PaymentSum { get; set; }
		DbSet<v_PermitActivities> v_PermitActivities { get; set; }
		DbSet<v_PermitAlerts> v_PermitAlerts { get; set; }
		DbSet<v_Permits> v_Permits { get; set; }
		DbSet<v_PermitsReport> v_PermitsReport { get; set; }
		DbSet<v_PhoneList> v_PhoneList { get; set; }
		DbSet<v_Preplans> v_Preplans { get; set; }
		DbSet<v_ProjectActivitySearch> v_ProjectActivitySearch { get; set; }
		DbSet<v_ProjectAddressSearch> v_ProjectAddressSearch { get; set; }
		DbSet<v_ProjectAlerts> v_ProjectAlerts { get; set; }
		DbSet<v_ProjectInspectorSearch> v_ProjectInspectorSearch { get; set; }
		DbSet<v_ProjectPermitSearch> v_ProjectPermitSearch { get; set; }
		DbSet<v_ProjectReport> v_ProjectReport { get; set; }
		DbSet<v_ProjectRequestSearch> v_ProjectRequestSearch { get; set; }
		DbSet<v_Projects> v_Projects { get; set; }
		DbSet<v_ROInspectionDetailsReports> v_ROInspectionDetailsReports { get; set; }
		DbSet<v_SearchActivities> v_SearchActivities { get; set; }
		DbSet<v_SearchActivities2> v_SearchActivities2 { get; set; }
		DbSet<v_SearchAddresses> v_SearchAddresses { get; set; }
		DbSet<v_SearchChecklist> v_SearchChecklist { get; set; }
		DbSet<v_SearchComplaintUDFs> v_SearchComplaintUDFs { get; set; }
		DbSet<v_SearchInspectionDetails> v_SearchInspectionDetails { get; set; }
		DbSet<v_SearchInvoices> v_SearchInvoices { get; set; }
		DbSet<v_SearchItems> v_SearchItems { get; set; }
		DbSet<v_SearchItems2> v_SearchItems2 { get; set; }
		DbSet<v_SearchItemsByParty> v_SearchItemsByParty { get; set; }
		DbSet<v_SearchPartiesBC> v_SearchPartiesBC { get; set; }
		DbSet<v_SearchPermits> v_SearchPermits { get; set; }
		DbSet<v_SearchProjects> v_SearchProjects { get; set; }
		DbSet<v_ServiceHistory> v_ServiceHistory { get; set; }
		DbSet<v_Signature> v_Signature { get; set; }
		DbSet<v_SignOffCompletes> v_SignOffCompletes { get; set; }
		DbSet<v_SignOffItems> v_SignOffItems { get; set; }
		DbSet<v_SnapshotFeesReport> v_SnapshotFeesReport { get; set; }
		DbSet<v_SubCheckItemValues> v_SubCheckItemValues { get; set; }
		DbSet<v_SubInspection> v_SubInspection { get; set; }
		DbSet<v_SubInspectionList> v_SubInspectionList { get; set; }
		DbSet<v_SubInspectionsReport> v_SubInspectionsReport { get; set; }
		DbSet<v_UserDefValues> v_UserDefValues { get; set; }
		DbSet<v_ViolationSearch> v_ViolationSearch { get; set; }
		DbSet<cv_CPTKHotlist> cv_CPTKHotlist { get; set; }

	}
}
