using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using NMSFM.Data;
using NMSFM.ViewModels;

namespace NMSFM.Services.FireGrant
{
    public interface IFGApplicationServices
    {
        Task<List<nm_FGApplication>> GetAllFGApplicationByFYAsync(short FiscalYear);
        Task<GrantYearStats> GetGrantYearStats(short FiscalYear);
        Task<List<nm_FGApplicationReport>> GetFGApplicationReportAsync();
        Task<List<nm_FGApplication>> GetAllFGApplicationByAddressAsync(Guid addressId);
        Task<List<nm_FGApplication>> GetFGApplicationsAllAsync();
        Task<nm_FGApplication> GetFGApplicationAsync(Guid addressId, short FiscalYear);
        Task<DetailedFGAppValidation> GetDetailedFGApplicationValidationAsync(Guid applicationId);
        Task<DetailedFGAppScores> GetDetailedFGAppScoresAsync(Guid applicationId);
        Task<List<DetailedFGAppScores>> GetDetailedFGAppScoresAdminAsync(Guid applicationId);
        Task<DetailedFGAppScores> GetDetailedFGAppScoresCounselorAsync(Guid applicationId, Guid webUserId);
        nm_FGApplication GetFGApplication(Guid addressId, short FiscalYear);
        Task<FGApplications> GetFGApplicationById(Guid applicationId);
        Task<List<nm_FGApplication>> GetFGApplicationByCounty(string County, int FiscalYear);
        Task<bool> CreateNewApplication(FGApplications model);
        Task<bool> UpdateApplication(FGApplications model);
        Task<FG_App_GeneralInfo> GetFGApplicationGeneralInfoAsync(Guid applicationId);
        Task<FGApplications> GetNearestPriorApplicationWithGeneralInfoAsync(Guid addressId, Guid currentApplicationId);
        FG_App_GeneralInfo GetFGApplicationGeneralInfo(Guid applicationId);
        Task<bool> SaveGeneralInformationAsync(FG_App_GeneralInfo model);
        Task<FG_App_BudgetInfo> GetFGApplicationBudgetInfoAsync(Guid applicationId);
        FG_App_BudgetInfo GetFGApplicationBudgetInfo(Guid applicationId);
        Task<bool> SaveBudgetInformationAsync(FG_App_BudgetInfo model);
        Task<DetailedFGAppCommunityInfo> GetFGApplicationCommunityInfoAsync(Guid applicationId);
        Task<DetailedFGAppCommunityInfo> GetFGApplicationPriorYearCommunityInfoAsync(Guid addressId, Guid applicationId);
        FG_App_CommunityInfo GetFGApplicationCommunityInfo(Guid applicationId);
        Task<bool> SaveCommunityInformationAsync(DetailedFGAppCommunityInfo model);
        Task<FG_App_ResponseHistory> GetFGApplicationResponseHistoryAsync(Guid applicationId);
        FG_App_ResponseHistory GetFGApplicationResponseHistory(Guid applicationId);
        Task<bool> SaveResponseHistoryAsync(FG_App_ResponseHistory model);
        Task<DetailedFGWaterAvailability> GetFGApplicationWaterAvailabilityAsync(Guid applicationId);
        Task<DetailedFGWaterAvailability> GetFGApplicationPriorYearWaterAvailabilityAsync(Guid addressId, Guid applicationId);
        FG_App_WaterAvailability GetFGApplicationWaterAvailability(Guid applicationId);
        Task<bool> SaveWaterAvailabilityAsync(DetailedFGWaterAvailability model);
        Task<DetailedFGAppTraining> GetFGApplicationTrainingAsync(Guid applicationId);
        FG_App_Training GetFGApplicationTraining(Guid applicationId);
        FG_App_TrainingOpportunities GetFGApplicationTrainingOpportunity(Guid trainingId);
        Task<bool> SaveTrainingAsync(DetailedFGAppTraining model);
        Task<bool> SaveTrainingOpportunity(FG_App_TrainingOpportunities model);
        Task<bool> DeleteTrainingOpportunityAsync(Guid id);
        Task<DetailedFGApparatus> GetFGApplicationApparatusAsync(Guid applicationId);
        Task<DetailedFGApparatus> GetPriorFGApplicationApparatusAsync(Guid addressId, Guid applicationId);
        FG_App_Apparatus GetFGApplicationApparatus(Guid applicationId);
        Task<bool> SaveApparatusAsync(DetailedFGApparatus model);
        Task<DetailedFGCommunication> GetFGApplicationCommunicationAsync(Guid applicationId);
        Task<DetailedFGCommunication> GetFGApplicationPriorYearCommunicationAsync(Guid addressId, Guid applicationId);
        FG_App_Communication GetFGApplicatioCommunication(Guid applicationId);
        Task<bool> SaveCommunicationAsync(DetailedFGCommunication model);
        Task<DetailedFGAppHazardsThreats> GetFGApplicationHazardsThreatsAsync(Guid applicationId);
        Task<DetailedFGAppHazardsThreats> GetFGApplicationPriorYearHazardsThreatsAsync(Guid addressId, Guid applicationId);
        FG_App_HazardsThreats GetFGApplicationHazardsThreats(Guid applicationId);
        Task<bool> SaveHazardThreatsAsync(DetailedFGAppHazardsThreats model);
        Task<DetailedFGAppPPE> GetFGApplicationPPEAsync(Guid applicationId);
        FG_App_PPE GetFGApplicationPPE(Guid applicationId);
        Task<bool> SavePPEAsync(DetailedFGAppPPE model);
        Task<DetailedFGAppEquipmentNeeds> GetFGApplicationEquipmentNeedsAsync(Guid applicationId);
        FG_App_EquipmentNeeds GetFGApplicationEquipmentNeeds(Guid applicationId);
        Task<bool> SaveEquipmentNeedsAsync(DetailedFGAppEquipmentNeeds model);
        Task<FG_App_FundingJustification> GetFGApplicationFundingJustificationAsync(Guid applicationId);
        FG_App_FundingJustification GetFGApplicationFundingJustification(Guid applicationId);
        Task<bool> SaveFundingJustificationAsync(FG_App_FundingJustification model);
        Task<FG_App_ProjectBudget> GetFGApplicationProjectBudgetAsync(Guid applicationId);
        FG_App_ProjectBudget GetFGApplicationProjectBudget(Guid applicationId);
        Task<bool> SaveProjectBudgetAsync(FG_App_ProjectBudget model);
        Task<DetailedFGAppSigsDocs> GetFGApplicationDocsSigsAsync(Guid applicationId);
        FG_App_DocsSigs GetApplicationDocsSigs(Guid applicationId);
        Task<bool> SaveApplicationDocsSigsAsync(DetailedFGAppSigsDocs model);
        Task<FG_App_Documents> GetApplicationDocumentByIdAsync(Guid id);
        Task<List<FG_AppDocListItem>> GetApplicationDocumentsByTypesAsync(
            Guid applicationId, string[] documentTypes);
        Task<bool> SaveApplicationDocumentAsync(FG_App_Documents model);
        Task<bool> DeleteApplicationDocumentAsync(Guid id);
        Task<bool> SaveApplicationSignatures(FG_App_Signatures model);
        Task<FG_App_Signatures> GetReviewerSignature(string applicationId);
        Task<FG_App_Signatures> GetCounselorSignature(string applicationId);
        Task<FG_App_Signatures> GetSignatorByToken(string applicationId, string loginToken);
        Task<DetailedFGAppReview> GetFGApplicationReviewAsync(Guid applicationId);
        FG_App_Review GetApplicationReview(Guid applicationId);
        Task<bool> SaveApplicationReviewAsync(DetailedFGAppReview model, bool fromStatus = false);
        Task<bool> SaveCounselorScores(DetailedFGAppScores model);
        Task<v_Addresses2> GetRemittanceAddress(bool isCity, string deptName);
    }
}
